// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'placeholder';


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    if (supabaseKey) {
      headers.set('apikey', supabaseKey);
    }

    try {
      return await fetch(input, { ...init, headers });
    } catch (err) {
      console.warn('[Supabase Fetch Error Intercepted]:', err);
      const urlStr = typeof input === 'string' ? input : (input && 'url' in input ? (input as Request).url : '');

      if (urlStr.includes('/auth/v1/')) {
        return new Response(
          JSON.stringify({
            error: {
              message: 'Network connection unavailable or server unreachable.',
              name: 'AuthApiError',
              status: 503,
            },
            user: null,
            session: null,
          }),
          {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
          }
        );
      }

      return new Response(
        JSON.stringify({
          message: 'Network connection unavailable',
          code: 'FETCH_ERROR',
          details: 'Failed to fetch',
          hint: 'Please check backend connectivity',
        }),
        {
          status: 503,
          headers: {
            'Content-Type': 'application/json',
            'content-range': '0-0/0',
          },
        }
      );
    }
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
